sudo: required
dist: trusty
services:
- docker
language: node_js
node_js:
- '4.5'

# Does not work as of yet, commenting out
#install:
#- export DISPLAY=:99.0
#- sh -e /etc/init.d/xvfb start
#- wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key
#  add -
#- sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable
#  main" >> /etc/apt/sources.list.d/google-chrome.list'
#- sudo apt-get update -q
#- sudo apt-get install -q google-chrome-stable
#before_script:
#- npm install
#script:
#- npm run test-single-run
#- "(npm start > /dev/null &) && (npm run protractor)"

# Simply install packages.
script:
- npm install

deploy:
- provider: script
  script: bash docker/docker_build_dev.sh
  on:
    branch: development
  skip_cleanup: true
- provider: script
  script: bash docker/docker_build_release.sh
  on:
    tags: true
  skip_cleanup: true
env:
  global:
  - secure: "ElwPqNXJSMRxvejqsyHEuCnxZ0Di7PlUf2++bBSeYfT/86ReSfGqHIUlo0MbNCORVGRZHoN1iZPq9FqvuTrWLw4s7uPbDrCWoRD4MVzPlu33+XsqjOPMivEsr90tkqhmepXfljx3tZWKZtbrna9aS+kaR9+lNUeOZsj3QVlUpLsbNWHPByYIOv6jHPFkMtLTVuiF0OEY9xMYVcnY3zeb+riNfJNbFPWJIRBXnF9ne3LWTXa9zFWJL7ChTP2VNI1ur0hN5PFAUF9ETHzbHPoOCYwKmMxk8O/ZuJhnP92+B/CAj2K3Aj3TEXedsSt0+Ft4UZz9fdlGQS1QJIXyJhZSFwGmzcapym0j/jNI69riv0drIIrrvooB8uqBByu76hHKUjT0EFhisr2c/Gan+3rN4FXKe5T4FAdby8AaoLhnuD4rvKYGHZw2/+P2pcGljJSFNz+3oM3+OFJH4A51wYDQF0yNlQ8S0x6zhBILuneCMWU2yw2vd0KjAWnZQOTlC2Zz5aGgtmESuqOWlI4ZB2gMZF1S1pauRSReS6UImbOcI1vzDv02OFMInX1swHqmEuLFhV5g4Xrtm5M7n1aZ484a1z1waDSdijHLh+MMfqux4HH/xMQccYxtE18ZASwJMpQINhoqsTpZiaMuxyZRbRiSfapZ/KzkzKajN+TVqOh07k4="
  - secure: "FJTOruqoryHA29u+4AY1g8PjF90CH11XdJvDcSeoJo46NbsR0cU/P2oTK6vZJgkEDyOiL4VBwEf0ZE3gsKza64+1a8s1YRDYJ79d15oP7QPfc3ugEmOGHYBMjnOCgd6/jAFmBRdl10+iVDsCaplrhxi1j0D/ubWGAGAKUnQTkIbHGMIg8Afm8kDpWGzM63Ljlyu5EduTWD+OOr18+8gS0StM+Wgc3t5R/PfAJj07ontX8+i5f+6B6WmCCYR6TimPsrl0Vi3h83JkDr6dE2wSfvvNCmio6n8fAItcDFuSjAeTQUYj0d8qQz3tmAKpVnF51gOpYm2lEXMbkJLVJZxM4cXLG7plAXsPVvTKv6PvRv7sH2/nOl8JYPCKdrUj/elM6EZTwRik6Rz+zZjyOTLU6jRrp9gc3wTbmon9kVMiPFaq9bnePqW/yQjtPPvN6tVz8XMcCz913XiQUOAQh1IOHWCw8HE4X7AnUuSqEgiUv970D6B2kSyMapS1lPrsX6HaTWdd1jvfWmEhKMAqgXp1/3qi44cMBtWcSMEkP7frikpLpjZavytsxcZNvuOPlGpH8kYmY9yvOU7vfws+Oz6sGbfzOnj2bAfldFtwIIIi1lkXE+k65VtVpWKS6XNjZA8aAhkFW2ocC66Fqc/jkzBDg0tCuQtMp5ziii7QM3jLAyA="
