sudo: required
dist: trusty
services:
- docker
language: node_js
node_js:
- '4.5'

# Does not work as of yet, commenting out
#install:
#- export DISPLAY=:99.0
#- sh -e /etc/init.d/xvfb start
#- wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key
#  add -
#- sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable
#  main" >> /etc/apt/sources.list.d/google-chrome.list'
#- sudo apt-get update -q
#- sudo apt-get install -q google-chrome-stable
#before_script:
#- npm install
#script:
#- npm run test-single-run
#- "(npm start > /dev/null &) && (npm run protractor)"

# Simply install packages.
script:
- npm install

deploy:
- provider: script
  script: bash docker/docker_build_dev.sh
  on:
    branch: development
  skip_cleanup: true
- provider: script
  script: bash docker/docker_build_release.sh
  on:
    tags: true
  skip_cleanup: true
env:
  global:
  - secure: dXu8D4fE5JQPvYNwqRsXLz71vwRu7RoiUlxtLdCKxa2DWQB+QaBg3dbONlvMUbv5TAKGsrN2kDPvYBd81FaRvM1sRp9ioZdD7m1h2edLE5Xw/DTqPvr6kinMC9Z16DI3nghSLFj+HhfL/fBHJXBrCnVxdyvsYH5RUTKv2j/VYuh4PbZ3EPZfqQASZ2qunlfsr7tMbLaNAfFgDErUgthOuRR6FfkBf7fRzGcF/ZSvM65S/QqsmVQD/lDxylAd49CNYpU+V6Zex3iHSh36NfAPgmjNLzbjpGZTX9DCWdpBrr94NtuLXpgnaB9zF+W/XSYawjfdwili7LHzIevKlHCKAi1skcBidC/rtMydds38i/8oVeBnWVKUFAAebl8OoDOSbh/YAYEBLldFkhVXlOQB9KeyiGbuyd0kiLM/Ba7KjavyS827q5aZzw4h+iFtwWbxYeNXcQyjqv7X4ygO+z03ho8MOWbDWsq7M4SqsRnE0vnS7Y0vLKA/KNBOaL3IwXfP+vHwQawnGM3hHnuZ1MfxHTacuid22zMveqYbcJSKSylnZy+xdDpVZsn61FNyT5mqaId897CvXwNCErtUM/kuoXd6SMpVqQJXuzBZj/TvtfCCoiFQFyaFXOrN9ipLuVLeqK9MW/7/zsMGkcP5R8Bx9I5T+qddnoThU7rYeoqhago=
  - secure: hoQXy4LgjFfLvyC0iGEZRJJpQHx9jKxagoPf7l+Oj8pZxFaz5ZUfmxAMjvJgvGVA9yRyfe8og2qI3KQGtW+lY9up92TOXNgkRSzavIhcWWNDAiakGhoDap1Hgr8PI1vdHue9mLbDd+kFASg9k3qw0gy7hmUcMkc1JJ65vaN/cJZq9dpFux77lwhgBuGun1Wf4vrIpddmtLPmi7HZH4OlAek9KKuNEQtqNQ2cfsC0T7XTuk/JXo52aQYaHUqQ3ls8voFi5/pJQztvtkjU130uBgrkYn3XUhWxB/0hwJZGZRdKzFXghYknNSXod8jttcLoNFiv4XJ5BGNkq1mndS6NsUxV7lIUhjNuNi3qch88x4EGnUufMdqO072zEdMJ74lGMBtTOUHVFJQDGhxIos4VwGm+plnZx/8GVHlW0o2Juok+S7gr3uu4NpR1jGlU/VE/BZpqbx54epCzfzn2d0rY1dKG2Rd++sgKAA2xm8/pj306ueuU6MEMcsTOV9ZCgjUZpI+nqM9vsLE4jTF9BWQJrR/cd7JTtI5KFDG02xo9HOIVUFxl32aWDyesXI3cykeVrBClqAVGWroaSaOUTUzTfTcWLTeONXf7T+NKhmgyDb5eWXqVXTEUJUYFbatzhZ9rJ3a7ebLmzYslVy+Fn5WaOUke3MOAVsxkVEAGL6EQXsg=
